width: 1920
height: 1080
marker_path: ""
bag_file: ""
bag_topic: ""
bag_fps: 60

# server/client
server_addr: ""
server_frame_port: 49992
server_message_port: 49993
server_decoder: "h264_cuvid"
server_encoder: "h264_nvenc"

client_addr: ""
client_frame_port: 49994
client_message_port: 49995
client_decoder: "h264"
client_encoder: "libx264"

