cam_dev_idx: 0

# For img_loader example
# ex) image_000001.png
#   - stem: image_
#   - start idx: 1
#   - max place value: 6
img_dir: ""
img_file_stem: ""
img_start_idx: 1
img_max_place_value: 6

# For bag example
bag_file: ""
bag_topic: ""
bag_fps: 30

width: 1920
height: 1080

# server/client
server_addr: "127.0.0.1"
server_frame_port: 49992
server_message_port: 49993
server_decoder: "h264_cuvid"
server_encoder: "h264_nvenc"

client_addr: "127.0.0.1"
client_frame_port: 49994
client_message_port: 49995
client_decoder: "h264_cuvid"
client_encoder: "h264_nvenc"

